# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('IdAdres', models.AutoField(primary_key=True, serialize=False)),
                ('Ulica', models.CharField(max_length=255)),
                ('Numer', models.CharField(max_length=30)),
                ('Mieszkanie', models.CharField(max_length=30)),
                ('KodPocztowy', models.CharField(max_length=30)),
                ('Miejscowosc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artykul',
            fields=[
                ('IdArtykul', models.AutoField(primary_key=True, serialize=False)),
                ('tytul', models.CharField(max_length=30)),
                ('tresc', models.CharField(max_length=1000)),
                ('Zamieszczenie', models.DateTimeField(default=django.utils.timezone.now)),
                ('IdAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('IdZdjecia', models.AutoField(primary_key=True, serialize=False)),
                ('Zdjecie', models.FileField(upload_to='')),
                ('IdAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Harmonogram_Startow',
            fields=[
                ('IdHS', models.AutoField(primary_key=True, serialize=False)),
                ('Opis', models.CharField(max_length=256)),
                ('Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Czas', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Harmonogram_Zawodow',
            fields=[
                ('IdH', models.AutoField(primary_key=True, serialize=False)),
                ('Opis', models.CharField(max_length=256)),
                ('Termin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Harmonogram_Zespol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdZ_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uczelnia', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Telefon', models.CharField(max_length=30)),
                ('Adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Adres')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wyniki_Zawodow',
            fields=[
                ('IdWynikow', models.AutoField(primary_key=True, serialize=False)),
                ('Czas', models.DateTimeField(default=django.utils.timezone.now)),
                ('IdHs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow')),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('IdZ', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=30)),
                ('Nazwisko', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zawody',
            fields=[
                ('IdZawody', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('IdZ', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=30)),
                ('Typ', models.CharField(max_length=30)),
                ('IdHS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow')),
                ('IdU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zespol_Zawody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdZ_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol')),
                ('IdZawody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody')),
            ],
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='IdZ_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol'),
        ),
        migrations.AddField(
            model_name='wyniki_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol'),
        ),
        migrations.AddField(
            model_name='harmonogram_zespol',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol'),
        ),
        migrations.AddField(
            model_name='harmonogram_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody'),
        ),
    ]
