# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Harmonogram_Startow',
            fields=[
                ('IdHS', models.AutoField(primary_key=True, serialize=False)),
                ('Opis', models.CharField(max_length=256)),
                ('Data', models.DateTimeField(default=django.utils.timezone.now)),
                ('Czas', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Harmonogram_Zawodow',
            fields=[
                ('IdH', models.AutoField(primary_key=True, serialize=False)),
                ('Opis', models.CharField(max_length=256)),
                ('Termin', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Zawody',
            fields=[
                ('IdZawody', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='harmonogram_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody'),
        ),
        migrations.AddField(
            model_name='harmonogram_startow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody'),
        ),
    ]
