# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 16:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('IdZ', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=30)),
                ('Nazwisko', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('IdZ', models.AutoField(primary_key=True, serialize=False)),
                ('Nazwa', models.CharField(max_length=30)),
                ('Typ', models.CharField(max_length=30)),
                ('IdHS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow')),
                ('IdU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zespol_Zawody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdZ_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol')),
                ('IdZawody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody')),
            ],
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='IdZ_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol'),
        ),
    ]
