# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artykul',
            name='Zamieszczenie',
        ),
    ]
