# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_auto_20170401_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harmonogram_startow',
            name='IdZawody',
        ),
        migrations.AddField(
            model_name='zespol_zawody',
            name='Wyniki',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZ_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow'),
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol'),
        ),
    ]
