# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_remove_artykul_zamieszczenie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawody',
            name='Nazwa',
            field=models.CharField(max_length=30, verbose_name=b'Nazwa zespo\xc5\x82u'),
        ),
    ]
