# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0002_auto_20170422_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki_zawodow',
            name='IdZespol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name='Identyfikator zawodów'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody'),
        ),
    ]
