# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_auto_20170424_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='Czas',
            field=models.CharField(max_length=13),
        ),
    ]
