# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-01 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0003_auto_20170501_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='tresc',
            field=models.TextField(max_length=1000, verbose_name=b'Tre\xc5\x9b\xc4\x87'),
        ),
    ]
