# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_auto_20170418_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artykul',
            options={'verbose_name_plural': 'Artyku\u0142y'},
        ),
    ]
