# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_auto_20170501_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiadomosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('tresc', models.TextField(max_length=1000, verbose_name=b'Tre\xc5\x9b\xc4\x87')),
            ],
            options={
                'verbose_name_plural': 'Wiadomo\u015bci',
            },
        ),
    ]
