# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_auto_20170418_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='harmonogram_startow',
            options={'verbose_name_plural': 'Harmonogram Start\xf3w'},
        ),
        migrations.AlterModelOptions(
            name='harmonogram_zawodow',
            options={'verbose_name_plural': 'Harmonogram Zawod\xf3w'},
        ),
        migrations.AlterModelOptions(
            name='harmonogram_zespol',
            options={'verbose_name_plural': 'Harmonogram zespo\u0142\xf3w'},
        ),
        migrations.AlterModelOptions(
            name='wyniki_zawodow',
            options={'verbose_name_plural': 'Wyniki zawod\xf3w'},
        ),
        migrations.AlterModelOptions(
            name='zawodnik',
            options={'verbose_name_plural': 'Zawodnicy'},
        ),
        migrations.AlterModelOptions(
            name='zespol',
            options={'verbose_name_plural': 'Zespo\u0142y'},
        ),
        migrations.AlterModelOptions(
            name='zespol_zawody',
            options={'verbose_name_plural': 'Zawodnicy w zespo\u0142ach'},
        ),
        migrations.AlterField(
            model_name='adres',
            name='KodPocztowy',
            field=models.CharField(max_length=30, verbose_name=b'Kod Pocztowy'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='Miejscowosc',
            field=models.CharField(max_length=255, verbose_name=b'Miejscowo\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='tresc',
            field=models.CharField(max_length=1000, verbose_name=b'Tre\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='tytul',
            field=models.CharField(max_length=30, verbose_name=b'Tytu\xc5\x82'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody', verbose_name=b'Numer zawod\xc3\xb3w'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zawodow',
            name='Opis',
            field=models.CharField(max_length=256, verbose_name=b'Opis wydarzenia'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zawodow',
            name='Termin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Termin wykonania'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zespol',
            name='IdZ_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow', verbose_name=b'Identyfikator startu'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zespol',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name=b'Identyfikator zespo\xc5\x82u'),
        ),
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='IdHs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow', verbose_name=b'Numer wy\xc5\x9bcigu'),
        ),
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name=b'Identyfikator zawod\xc3\xb3w'),
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZ_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name=b'Identyfikator zespo\xc5\x82u'),
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody', verbose_name=b'Identyfikator zawod\xc3\xb3w'),
        ),
    ]
