# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0005_wiadomosci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='Miejscowosc',
            field=models.CharField(max_length=255, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='tresc',
            field=models.TextField(max_length=1000, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='tytul',
            field=models.CharField(max_length=30, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='Zdjecie',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='harmonogram_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody', verbose_name='Numer zawodów'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zespol',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name='Identyfikator zespołu'),
        ),
        migrations.AlterField(
            model_name='wiadomosci',
            name='tresc',
            field=models.TextField(max_length=1000, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='IdHs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow', verbose_name='Numer wyścigu'),
        ),
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name='Identyfikator zawodów'),
        ),
        migrations.AlterField(
            model_name='zawody',
            name='Nazwa',
            field=models.CharField(max_length=30, verbose_name='Nazwa zespołu'),
        ),
        migrations.AlterField(
            model_name='zespol',
            name='IdHS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow', verbose_name='Identyfikator startów'),
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZ_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name='Identyfikator zespołu'),
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody', verbose_name='Identyfikator zawodów'),
        ),
    ]
