# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0004_auto_20170424_1439'),
        ('MainSite', '0007_auto_20170504_1748'),
    ]

    operations = [
    ]
