# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0009_auto_20170508_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wyniki_zawodow',
            old_name='IdZespolu',
            new_name='IdZespol',
        ),
    ]
