# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0010_auto_20170508_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
