# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0011_auto_20170508_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Adres',
        ),
        migrations.AddField(
            model_name='profile',
            name='KodPocztowy',
            field=models.CharField(default=0, max_length=30, verbose_name='Kod Pocztowy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Miejscowosc',
            field=models.CharField(default='', max_length=255, verbose_name='Miejscowość'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Mieszkanie',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Numer',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Ulica',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Adres',
        ),
    ]
