# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainSite', '0012_auto_20170515_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artykul',
            name='tresc',
            field=models.TextField(max_length=1000, verbose_name=b'Tre\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='artykul',
            name='tytul',
            field=models.CharField(max_length=30, verbose_name=b'Tytu\xc5\x82'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody', verbose_name=b'Numer zawod\xc3\xb3w'),
        ),
        migrations.AlterField(
            model_name='harmonogram_zespol',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name=b'Identyfikator zespo\xc5\x82u'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Miejscowosc',
            field=models.CharField(max_length=255, verbose_name=b'Miejscowo\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='wiadomosci',
            name='tresc',
            field=models.TextField(max_length=1000, verbose_name=b'Tre\xc5\x9b\xc4\x87'),
        ),
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='IdHs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow', verbose_name=b'Numer wy\xc5\x9bcigu'),
        ),
        migrations.AlterField(
            model_name='wyniki_zawodow',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody', verbose_name=b'Identyfikator zawod\xc3\xb3w'),
        ),
        migrations.AlterField(
            model_name='zawody',
            name='Nazwa',
            field=models.CharField(max_length=30, verbose_name=b'Nazwa zespo\xc5\x82u'),
        ),
        migrations.AlterField(
            model_name='zespol',
            name='IdHS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Harmonogram_Startow', verbose_name=b'Identyfikator start\xc3\xb3w'),
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZ_0',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zespol', verbose_name=b'Identyfikator zespo\xc5\x82u'),
        ),
        migrations.AlterField(
            model_name='zespol_zawody',
            name='IdZawody',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainSite.Zawody', verbose_name=b'Identyfikator zawod\xc3\xb3w'),
        ),
    ]
